# This is a basic workflow to help you get started with Actions
name: 01 - Building Block

on:
  #push:
  workflow_dispatch:

jobs:
  echo-hello:
    runs-on: ubuntu-latest

    steps:
      - name: Say hello
        run: echo "Hello, world"
  echo-goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: Success step
        run: |
          echo "I"
          echo "Will"
          echo "success"
          exit 0
      - name: Say goodbye
        run: echo "GoodBye!"
