name: 02 - Workflow Events

on:
  #push:
  #pull_request:
  #workflow_dispatch:
  schedule:
    - cron: '54 16 24 12 2'

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "${{ github.event_name }}"
    
