name: 04-Multi-Environments

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Set environment-specific variables
        run: |
          if [ ${{ github.ref }} = 'refs/heads/main' ]; then
            echo "${{ vars.PRODUCTION_API_URL }}" >> $GITHUB_ENV
          elif [ ${{ github.ref }} = 'refs/heads/develop' ]; then
            echo "${{ vars.STAGING_API_URL}}" >> $GITHUB_ENV
          fi
          echo "VERSION=v1.2.0" >> $GITHUB_ENV
      - name: Deploy application
        run: | 
          if [ ${{ github.ref }} = 'refs/heads/main' ]; then
            echo "Deploying to Production"
          elif [ ${{ github.ref }} = 'refs/heads/develop' ]; then
            echo "Deploying to Staging"
          fi
          
  
